# Generated by Django 5.0.6 on 2024-07-10 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registration', 'Регистрация'), ('active', 'Активен'), ('pause', 'Пауза'), ('stop', 'СТОП')], help_text='Статус оффера', max_length=20, verbose_name='Статус')),
                ('logo', models.ImageField(help_text='Логотип оффера', upload_to='logos/', verbose_name='Логотип')),
                ('name', models.CharField(help_text='Название оффера', max_length=255, verbose_name='Название')),
                ('legal_name', models.CharField(help_text='Юридическое название оффера', max_length=255, verbose_name='Юридическое название')),
                ('inn', models.CharField(help_text='ИНН оффера', max_length=20, verbose_name='ИНН')),
                ('contract_number', models.CharField(help_text='Номер договора оффера', max_length=50, verbose_name='Номер договора')),
                ('contract_date', models.DateField(help_text='Дата договора оффера', verbose_name='Дата договора')),
                ('license', models.FileField(help_text='Лицензия оффера', upload_to='licenses/', verbose_name='Лицензия')),
                ('official_website', models.URLField(help_text='Официальный сайт оффера', verbose_name='Официальный сайт')),
                ('legal_address', models.TextField(help_text='Юридический адрес оффера', verbose_name='Юридический адрес')),
                ('actual_address', models.TextField(help_text='Фактический адрес оффера', verbose_name='Фактический адрес')),
                ('working_hours', models.CharField(help_text='Режим работы оффера', max_length=255, verbose_name='Режим работы')),
                ('description', models.TextField(help_text='Описание оффера', verbose_name='Описание')),
                ('geo', models.CharField(help_text='ГЕО оффера', max_length=255, verbose_name='ГЕО')),
                ('lead_validity', models.CharField(help_text='Валидность лида оффера', max_length=255, verbose_name='Валидность лида')),
                ('landing_page_url', models.URLField(help_text='Ссылка на посадочную страницу оффера', verbose_name='Ссылка на посадочную страницу')),
                ('post_request_docs', models.TextField(help_text='Документация по постзапросам оффера', verbose_name='Документация по постзапросам')),
                ('lead_price', models.DecimalField(decimal_places=2, help_text='Цена за лид оффера', max_digits=10, verbose_name='Цена за лид')),
                ('partner', models.ForeignKey(help_text='Партнер, связанный с оффером', on_delete=django.db.models.deletion.CASCADE, to='partner_management.partner', verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Оффер',
                'verbose_name_plural': 'Офферы',
            },
        ),
    ]
