version: '3.8'

services:
  # Сервис для Redis
  redis:
    image: "redis:alpine"
    container_name: "redis"
    ports:
      - "6379:6379"  # Порт Redis

  # Сервис для Celery
  celery:

    container_name: "celery"
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A AdStart worker --loglevel=info  # Замените на имя вашего проекта
    depends_on:
      - redis
    volumes:
      - .:/app  # Монтируем текущую папку
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  # Сервис для Django
  django:
    build: .
    image: django:latest
    container_name: "django"
    command: gunicorn AdStart.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # Порт Django
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0