# Generated by Django 5.0.6 on 2024-07-10 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer_management', '0001_initial'),
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название сайта', max_length=255, verbose_name='Название')),
                ('archive', models.FileField(help_text='Архив сайта', upload_to='archives/', verbose_name='Архив')),
                ('landing_type', models.CharField(choices=[('land', 'Ленд'), ('quiz', 'Квиз'), ('clip', 'Клип')], help_text='Тип посадки сайта', max_length=20, verbose_name='Тип посадки')),
                ('status', models.CharField(choices=[('in_work', 'В работе'), ('on_pause', 'На паузе'), ('disabled', 'Выключена')], help_text='Статус сайта', max_length=20, verbose_name='Статус')),
                ('path', models.CharField(help_text='Путь к сайту на сервере', max_length=255, verbose_name='Путь')),
                ('offer', models.ForeignKey(help_text='Оффер, связанный с сайтом', on_delete=django.db.models.deletion.CASCADE, to='offer_management.offer', verbose_name='Оффер')),
                ('webmaster', models.ForeignKey(help_text='Вебмастер, связанный с сайтом', on_delete=django.db.models.deletion.CASCADE, to='user_accounts.webmaster', verbose_name='Вебмастер')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты',
            },
        ),
    ]
