# Generated by Django 5.0.6 on 2024-11-24 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('out', 'вывод'), ('in', 'ввод')], default='registered', max_length=20, verbose_name='Вид выплаты')),
                ('status', models.CharField(choices=[('in_processing', 'В проссе'), ('success', 'Успешно')], default='registered', max_length=20, verbose_name='Статус заявки')),
                ('count', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма выплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
