# Generated by Django 5.0.6 on 2024-07-10 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории', max_length=255, verbose_name='Название')),
                ('is_private', models.BooleanField(default=False, help_text='Флаг приватности категории', verbose_name='Приватная')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='Логотип партнера', upload_to='logos/', verbose_name='Логотип')),
                ('name', models.CharField(help_text='Название партнера', max_length=255, verbose_name='Название')),
                ('legal_name', models.CharField(help_text='Юридическое название партнера', max_length=255, verbose_name='Юридическое название')),
                ('license', models.FileField(help_text='Лицензия партнера', upload_to='licenses/', verbose_name='Лицензия')),
                ('official_website', models.URLField(help_text='Официальный сайт партнера', verbose_name='Официальный сайт')),
                ('legal_address', models.TextField(help_text='Юридический адрес партнера', verbose_name='Юридический адрес')),
                ('actual_address', models.TextField(help_text='Фактический адрес партнера', verbose_name='Фактический адрес')),
                ('company_details', models.TextField(help_text='Реквизиты компании партнера', verbose_name='Реквизиты компании')),
                ('phone', models.CharField(help_text='Основной телефон партнера', max_length=20, verbose_name='Телефон')),
                ('deposit', models.DecimalField(decimal_places=2, help_text='Депозит партнера', max_digits=10, verbose_name='Депозит')),
                ('admin_user', models.ForeignKey(help_text='Администратор, связанный с партнером', on_delete=django.db.models.deletion.CASCADE, to='user_accounts.customadminuser', verbose_name='Администратор')),
                ('advertiser_user', models.ForeignKey(help_text='Рекламодатель, связанный с партнером', on_delete=django.db.models.deletion.CASCADE, to='user_accounts.advertiser', verbose_name='Рекламодатель')),
            ],
            options={
                'verbose_name': 'Карточка рекламодателя',
                'verbose_name_plural': 'Карточки рекламодателей',
            },
        ),
    ]
