# Generated by Django 5.0.6 on 2024-07-15 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner_cards', '0001_initial'),
        ('user_accounts', '0003_alter_advertiser_user_alter_webmaster_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registration', 'Регистрация'), ('active', 'Активен'), ('pause', 'Пауза'), ('stop', 'СТОП')], default='registration', max_length=20, verbose_name='Актуальность')),
                ('public_status', models.CharField(choices=[('closed', 'Закрытый'), ('public', 'Публичный')], default='closed', max_length=20, verbose_name='Статус оффера')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='offer_logos/', verbose_name='Логотип')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('legal_name', models.CharField(max_length=255, verbose_name='Наименование Юр. лица')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('contract_number', models.CharField(max_length=50, verbose_name='Номер Договора')),
                ('contract_date', models.DateField(verbose_name='Дата Договора')),
                ('license', models.FileField(blank=True, null=True, upload_to='offer_licenses/', verbose_name='Лицензия')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Ссылка на официальный сайт')),
                ('legal_address', models.CharField(max_length=255, verbose_name='Юридический адрес')),
                ('actual_addresses', models.TextField(blank=True, null=True, verbose_name='Фактический адрес')),
                ('working_hours', models.CharField(max_length=255, verbose_name='Режим работы')),
                ('service_description', models.TextField(verbose_name='Описание услуг по офферу')),
                ('geo', models.CharField(max_length=255, verbose_name='ГЕО')),
                ('lead_validity', models.CharField(max_length=255, verbose_name='Валидность лида')),
                ('landing_page', models.URLField(blank=True, null=True, verbose_name='Ссылка на посадку')),
                ('postback_documentation', models.TextField(verbose_name='Документация по отправке постзапросов')),
                ('lead_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за лид')),
                ('assigned_webmasters', models.ManyToManyField(blank=True, related_name='assigned_offers', to='user_accounts.webmaster', verbose_name='Назначенные вебмастеры')),
                ('partner_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='partner_cards.partnercard')),
            ],
            options={
                'verbose_name': 'Оффер',
                'verbose_name_plural': 'Офферы',
            },
        ),
    ]
