# Generated by Django 5.0.6 on 2025-01-30 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadwall',
            name='webmaster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user_accounts.webmaster', verbose_name='Вебмастер'),
        ),
    ]
