# Generated by Django 5.0.6 on 2024-07-15 15:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
        ('partner_cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='assigned_webmasters',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='contract_number',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='license',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='logo',
        ),
        migrations.AlterField(
            model_name='offer',
            name='contract_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата договора'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='geo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ГЕО'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='lead_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за лид'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='lead_validity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Валидность лида'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='partner_card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='partner_cards.partnercard'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='postback_documentation',
            field=models.TextField(blank=True, null=True, verbose_name='Документация по отправке постзапросов'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='public_status',
            field=models.CharField(choices=[('private', 'Закрытый'), ('public', 'Публичный')], default='private', max_length=20, verbose_name='Публичный статус'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('registered', 'Регистрация'), ('active', 'Активен'), ('paused', 'Пауза'), ('stopped', 'СТОП')], default='registered', max_length=20, verbose_name='Актуальность'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Режим работы'),
        ),
    ]
