# Generated by Django 5.0.6 on 2025-01-30 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_leadwall_webmaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadwall',
            name='webmaster',
        ),
    ]
