# Generated by Django 5.0.6 on 2024-12-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20241202_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerarchive',
            name='cloned_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата клонирования'),
        ),
    ]
