# Generated by Django 5.0.6 on 2024-07-24 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_offer_contract_number_offer_inn_offer_license_and_more'),
        ('partner_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='partner_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='partner_cards.partnercard'),
        ),
    ]
