# Generated by Django 5.0.6 on 2025-02-03 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_leadwall_webmaster_alter_leadwall_offer_webmaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadwall',
            name='webmaster',
        ),
    ]
