# Generated by Django 5.0.6 on 2024-07-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_offer_partner_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='actual_addresses',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='landing_page',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='lead_validity',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='legal_address',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='legal_name',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='license',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='postback_documentation',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='website',
        ),
        migrations.AlterField(
            model_name='offer',
            name='contract_number',
            field=models.CharField(max_length=50, verbose_name='Номер Договора'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование оффера'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Режим работы колл-центра'),
        ),
    ]
