# Generated by Django 5.0.6 on 2024-07-24 14:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_remove_offer_actual_addresses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='contract_number',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True, verbose_name='Номер Договора'),
        ),
    ]
