# Generated by Django 5.0.6 on 2024-07-24 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_alter_offer_contract_number'),
        ('user_accounts', '0003_alter_advertiser_user_alter_webmaster_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='webmaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='user_accounts.webmaster'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='contract_number',
            field=models.CharField(default='AUTO_GENERATE', max_length=50, verbose_name='Номер Договора'),
        ),
    ]
