# Generated by Django 5.0.6 on 2024-07-24 16:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_offer_webmaster_alter_offer_contract_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='unique_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Уникальный токен'),
        ),
    ]
