# Generated by Django 5.0.6 on 2024-07-24 16:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_offer_unique_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='unique_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный токен для определения связи между оффером и вебмастером', unique=True, verbose_name='Уникальный токен'),
        ),
    ]
