# Generated by Django 5.0.6 on 2024-08-06 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_alter_offer_unique_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadWall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер мобильного телефона')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Дополнительное поле')),
                ('status', models.CharField(choices=[('new', 'Новый лид'), ('expired', 'Просрочено'), ('paid', 'Оплачено'), ('no_response', 'Нет ответа'), ('on_hold', 'Холд'), ('callback', 'Перезвонить'), ('appointment', 'Запись на прием'), ('visit', 'Визит'), ('cancelled', 'Отмена'), ('trash', 'Треш'), ('duplicate', 'Дубль')], default='new', max_length=20, verbose_name='Статус лида')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_wall', to='offers.offer', to_field='unique_token', verbose_name='Оффер')),
            ],
            options={
                'verbose_name': 'Лидвол',
                'verbose_name_plural': 'Лидволы',
            },
        ),
    ]
