# Generated by Django 5.0.6 on 2024-08-07 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_leadwall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadwall',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_wall', to='offers.offer', to_field='unique_token', verbose_name='Оффер'),
        ),
    ]
