# Generated by Django 5.0.6 on 2024-08-09 15:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0011_alter_leadwall_offer'),
        ('user_accounts', '0003_alter_advertiser_user_alter_webmaster_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadwall',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='unique_token',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='webmaster',
        ),
        migrations.AddField(
            model_name='leadwall',
            name='processing_status',
            field=models.CharField(choices=[('new', 'Новый лид'), ('no_response', 'Нет ответа'), ('callback', 'Перезвонить'), ('appointment', 'Запись на прием'), ('visit', 'Визит'), ('trash', 'Треш'), ('duplicate', 'Дубль')], default='new', max_length=20, verbose_name='Статус обработки'),
        ),
        migrations.AlterField(
            model_name='leadwall',
            name='status',
            field=models.CharField(choices=[('expired', 'Просрочено'), ('paid', 'Оплачено'), ('on_hold', 'Холд'), ('cancelled', 'Отмена')], default='on_hold', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='OfferWebmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный токен для определения связи между оффером и вебмастером', unique=True, verbose_name='Уникальный токен')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webmaster_links', to='offers.offer')),
                ('webmaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_links', to='user_accounts.webmaster')),
            ],
            options={
                'verbose_name': 'Связь Оффер-Вебмастер',
                'verbose_name_plural': 'Связи Оффер-Вебмастер',
                'unique_together': {('offer', 'webmaster')},
            },
        ),
        migrations.AddField(
            model_name='leadwall',
            name='offer_webmaster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='offers.offerwebmaster', verbose_name='Оффер-Вебмастер'),
            preserve_default=False,
        ),
    ]
