# Generated by Django 5.0.6 on 2024-08-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0012_remove_leadwall_offer_remove_offer_unique_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadwall',
            name='processing_status',
            field=models.CharField(choices=[('new', 'Новый лид'), ('expired', 'Просрочено'), ('no_response', 'Нет ответа'), ('callback', 'Перезвонить'), ('appointment', 'Запись на прием'), ('visit', 'Визит'), ('trash', 'Треш'), ('duplicate', 'Дубль'), ('rejected', 'Отклонено')], default='new', max_length=20, verbose_name='Статус обработки'),
        ),
        migrations.AlterField(
            model_name='leadwall',
            name='status',
            field=models.CharField(choices=[('paid', 'Оплачено'), ('on_hold', 'В работе'), ('cancelled', 'Отмена')], default='on_hold', max_length=20, verbose_name='Статус'),
        ),
    ]
