# Generated by Django 5.0.6 on 2024-08-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0013_alter_leadwall_processing_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadwall',
            name='phone',
        ),
        migrations.AddField(
            model_name='offerwebmaster',
            name='phone',
            field=models.CharField(default=1, max_length=15, verbose_name='Номер мобильного телефона'),
            preserve_default=False,
        ),
    ]
