# Generated by Django 5.0.6 on 2024-08-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0014_remove_leadwall_phone_offerwebmaster_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadwall',
            name='phone',
            field=models.CharField(default=1, max_length=15, verbose_name='Номер мобильного телефона'),
            preserve_default=False,
        ),
    ]
