# Generated by Django 5.0.6 on 2024-08-25 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0016_leadwall_description_extra_leadwall_sub_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadwall',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Доменное имя отправителя'),
        ),
        migrations.AddField(
            model_name='leadwall',
            name='ip_adress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IP адрес отправителя'),
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время трекинга клика')),
                ('click_data', models.TextField(blank=True, null=True, verbose_name='Данные о клиенте')),
                ('offer_webmaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='offers.offerwebmaster', verbose_name='Оффер-Вебмастер')),
            ],
            options={
                'verbose_name': 'Клик',
                'verbose_name_plural': 'Клики',
            },
        ),
    ]
