# Generated by Django 5.0.6 on 2024-08-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0017_leadwall_domain_leadwall_ip_adress_click'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Доменное имя отправителя'),
        ),
        migrations.AddField(
            model_name='click',
            name='ip_adress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IP адрес отправителя'),
        ),
    ]
