# Generated by Django 5.0.6 on 2024-08-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0018_click_domain_click_ip_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='sub_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub 1'),
        ),
        migrations.AddField(
            model_name='click',
            name='sub_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub 2'),
        ),
        migrations.AddField(
            model_name='click',
            name='sub_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub 3'),
        ),
        migrations.AddField(
            model_name='click',
            name='sub_4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub 4'),
        ),
        migrations.AddField(
            model_name='click',
            name='sub_5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub 5'),
        ),
    ]
