# Generated by Django 5.0.6 on 2024-08-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0019_click_sub_1_click_sub_2_click_sub_3_click_sub_4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadwall',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
