# Generated by Django 5.0.6 on 2024-08-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0020_alter_leadwall_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadwall',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
