# Generated by Django 5.0.6 on 2024-08-31 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0021_leadwall_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadwall',
            name='comment',
        ),
    ]
