# Generated by Django 5.0.6 on 2024-09-10 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0023_leadcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField(max_length=255, verbose_name='URL репозитория')),
                ('branch', models.CharField(default='main', max_length=255, verbose_name='Ветка репозитория')),
                ('cloned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата клонирования')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='offers.offer')),
            ],
            options={
                'verbose_name': 'Архив оффера',
                'verbose_name_plural': 'Архивы офферов',
            },
        ),
    ]
