# Generated by Django 5.0.6 on 2024-09-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0024_offerarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerarchive',
            name='last_commit_hash',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Хеш последнего коммита'),
        ),
        migrations.AddField(
            model_name='offerarchive',
            name='local_repo_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к локальному репозиторию'),
        ),
    ]
