# Generated by Django 5.0.6 on 2024-12-02 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('confirmation_code', models.CharField(max_length=6, verbose_name='Код подтверждения')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(blank=True, help_text='Telegram аккаунт рекламодателя', max_length=50, null=True, verbose_name='Telegram')),
                ('phone', models.CharField(blank=True, help_text='Телефон рекламодателя', max_length=20, null=True, verbose_name='Телефон')),
                ('about', models.TextField(blank=True, help_text='Описание услуги', max_length=500, verbose_name='Описание услуги')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Категория рекламодателя', null=True, on_delete=django.db.models.deletion.CASCADE, to='user_accounts.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Рекламодатель',
                'verbose_name_plural': 'Рекламодатели',
            },
        ),
        migrations.CreateModel(
            name='Webmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(blank=True, help_text='Telegram аккаунт вебмастера', max_length=50, null=True, verbose_name='Telegram')),
                ('phone', models.CharField(blank=True, help_text='Телефон вебмастера', max_length=20, null=True, verbose_name='Телефон')),
                ('experience', models.TextField(blank=True, help_text='Опыт вебмастера', null=True, verbose_name='Опыт')),
                ('stats_screenshot', models.ImageField(blank=True, help_text='Скриншот статистики вебмастера', null=True, upload_to='screenshots/', verbose_name='Скриншот статистики')),
                ('is_approved', models.BooleanField(default=False, help_text='Подтверждение регистрации вебмастера, для передачи вебмастеру доступа к системе поставьте галочку в этом поле и сохраните изменения!', verbose_name='Подтверждение администратором')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вебмастер',
                'verbose_name_plural': 'Вебмастера',
            },
        ),
    ]
