# Generated by Django 5.0.6 on 2024-12-02 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
    ]
