# Generated by Django 5.0.6 on 2024-08-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0003_alter_advertiser_user_alter_webmaster_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webmaster',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс'),
        ),
    ]
