# Generated by Django 5.0.6 on 2024-10-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0004_webmaster_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='about',
            field=models.CharField(blank=True, help_text='Описание услуги', max_length=500, verbose_name='Описание услуги'),
        ),
    ]
