# Generated by Django 5.0.6 on 2024-07-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnercard',
            name='actual_addresses',
            field=models.TextField(verbose_name='Фактический адрес'),
        ),
        migrations.AlterField(
            model_name='partnercard',
            name='company_details',
            field=models.TextField(blank=True, null=True, verbose_name='Реквизиты компании'),
        ),
        migrations.AlterField(
            model_name='partnercard',
            name='website',
            field=models.URLField(verbose_name='Ссылка на официальный сайт'),
        ),
    ]
