# Generated by Django 5.0.6 on 2024-11-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('archive', models.FileField(upload_to='archives/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('extracted_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
