# Generated by Django 5.0.6 on 2024-11-26 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_category_sitearchive_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitearchive',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='sites.category'),
        ),
    ]
