# Generated by Django 5.0.6 on 2024-11-28 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
        ('sites', '0003_sitearchive_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='sitearchive',
            options={'verbose_name': 'Сайт', 'verbose_name_plural': 'Сайты'},
        ),
        migrations.AddField(
            model_name='sitearchive',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asd', to='offers.offer'),
        ),
        migrations.AlterField(
            model_name='sitearchive',
            name='archive',
            field=models.FileField(upload_to='archives/', verbose_name='Архив'),
        ),
        migrations.AlterField(
            model_name='sitearchive',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='sites.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='sitearchive',
            name='extracted_path',
            field=models.CharField(blank=True, default='extracted', max_length=255, verbose_name='Путь распаковки'),
        ),
        migrations.AlterField(
            model_name='sitearchive',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название архива/сайта'),
        ),
        migrations.AlterField(
            model_name='sitearchive',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='sitearchive',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
    ]
