# Generated by Django 5.0.6 on 2024-11-28 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
        ('sites', '0004_alter_category_options_alter_sitearchive_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitearchive',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_offer', to='offers.offer'),
        ),
    ]
