# Generated by Django 5.0.6 on 2024-11-28 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
        ('sites', '0005_alter_sitearchive_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitearchive',
            name='offer',
        ),
        migrations.AddField(
            model_name='sitearchive',
            name='offer_web',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_offer', to='offers.offerwebmaster'),
        ),
    ]
