# Generated by Django 5.0.6 on 2024-12-02 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
        ('sites', '0006_remove_sitearchive_offer_sitearchive_offer_web'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitearchive',
            name='offer_web',
        ),
        migrations.AddField(
            model_name='sitearchive',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_offer', to='offers.offer'),
        ),
    ]
